#!/usr/bin/env python
"""Start a deterministic full-stack environment for v3 e2e tests.

What it brings up (default ports):

    127.0.0.1:8099  mock LLM (scripts/mock_llm_server.py)
    127.0.0.1:8012  backend  (uvicorn + LLM_HOST → mock)
    127.0.0.1:3783  frontend (Next.js dev + NEXT_PUBLIC_API_BASE → backend)

Each port is offset from the dev environment (8011/3782 in .env) so this
launcher can run alongside ``scripts/start_web.py`` without conflict.

Usage:

    # Start everything; Ctrl-C stops cleanly.
    python scripts/start_e2e_env.py

    # In another shell, run e2e tests against the e2e env:
    cd web && WEB_BASE_URL=http://localhost:3783 npm run test:smoke

    # Run backend integration tests against the e2e env:
    PYTHONPATH=. .venv/bin/python -m pytest tests/integration -q

The script waits for each service to become reachable before declaring
"ready" — once you see "✓ All services ready" you can run tests.

Why deterministic? The mock LLM (scripts/mock_llm_server.py) returns
``[mock] reply to: <user message>`` for every prompt and HTTP 500 when
the user message starts with ``ERROR:``. e2e tests assert on this
fingerprint instead of real model output.
"""

from __future__ import annotations

import argparse
import contextlib
import os
import shutil
import signal
import socket
import subprocess
import sys
import threading
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEB_DIR = PROJECT_ROOT / "web"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _is_port_in_use(port: int, host: str = "127.0.0.1") -> bool:
    with contextlib.closing(
        socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    ) as sock:
        sock.settimeout(0.2)
        try:
            sock.connect((host, port))
        except (ConnectionRefusedError, OSError):
            return False
        return True


def _wait_for_port(port: int, host: str = "127.0.0.1", timeout_s: float = 30.0) -> bool:
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        if _is_port_in_use(port, host):
            return True
        time.sleep(0.25)
    return False


def _stream_to_stdout(prefix: str, process: subprocess.Popen[str]) -> None:
    """Tag every line from a subprocess so all 3 services share one log."""
    assert process.stdout is not None
    for line in process.stdout:
        sys.stdout.write(f"  {prefix}  {line}")
    sys.stdout.flush()


# ---------------------------------------------------------------------------
# Service launchers
# ---------------------------------------------------------------------------


def _start_mock_llm(port: int) -> subprocess.Popen[str]:
    return subprocess.Popen(
        [sys.executable, str(PROJECT_ROOT / "scripts" / "mock_llm_server.py"),
         "--port", str(port), "--host", "127.0.0.1"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        cwd=PROJECT_ROOT,
    )


def _write_e2e_env_file(path: Path, mock_llm_port: int, backend_port: int) -> None:
    """Write a sandboxed .env file the backend will read via DEEPTUTOR_ENV_FILE.

    env_store.EnvStore reads its values from the file in `self.path` (and
    file values *win* over os.environ — see env_store.py:get). Setting the
    LLM_HOST env var alone is therefore not enough; we have to feed the
    override through a real file the backend opens.
    """
    path.write_text(
        "\n".join(
            [
                "# Auto-generated by scripts/start_e2e_env.py",
                f"BACKEND_PORT={backend_port}",
                f"LLM_HOST=http://127.0.0.1:{mock_llm_port}/v1",
                "LLM_BINDING=openai",
                "LLM_MODEL=mock-model",
                "LLM_API_KEY=mock-key",
                f"EMBEDDING_HOST=http://127.0.0.1:{mock_llm_port}/v1/embeddings",
                "EMBEDDING_BINDING=openai",
                "EMBEDDING_MODEL=mock-embedding",
                "EMBEDDING_API_KEY=mock-key",
                "",
            ]
        ),
        encoding="utf-8",
    )


def _start_backend(
    port: int, mock_llm_port: int, env_file: Path
) -> subprocess.Popen[str]:
    """Launch the backend bound to *port* with LLM_HOST → mock.

    Bypasses ``deeptutor.api.run_server`` (it reads its port from .env via
    env_store and ignores BACKEND_PORT in os.environ). We invoke uvicorn
    directly with explicit --port and pass DEEPTUTOR_ENV_FILE so env_store
    sources its values from the sandboxed file written for this run, not
    the developer's real .env.
    """
    env = os.environ.copy()
    env["DEEPTUTOR_ENV_FILE"] = str(env_file)
    return subprocess.Popen(
        [
            sys.executable, "-m", "uvicorn",
            "deeptutor.api.main:app",
            "--host", "127.0.0.1",
            "--port", str(port),
            "--log-level", "warning",
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        cwd=PROJECT_ROOT,
        env=env,
    )


def _start_frontend(port: int, backend_port: int) -> subprocess.Popen[str]:
    npm = shutil.which("npm")
    if npm is None:
        raise RuntimeError("npm not found on PATH")
    env = os.environ.copy()
    env["NEXT_PUBLIC_API_BASE"] = f"http://localhost:{backend_port}"
    return subprocess.Popen(
        [npm, "run", "dev", "--", "--port", str(port)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        cwd=WEB_DIR,
        env=env,
    )


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def _check_ports_free(ports: dict[str, int]) -> None:
    busy = {name: port for name, port in ports.items() if _is_port_in_use(port)}
    if busy:
        msg = ", ".join(f"{name}={p}" for name, p in busy.items())
        raise SystemExit(f"✗ Ports already in use: {msg}. Stop other launchers first.")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mock-llm-port", type=int, default=8099)
    parser.add_argument("--backend-port", type=int, default=8012)
    parser.add_argument("--frontend-port", type=int, default=3783)
    parser.add_argument(
        "--no-frontend",
        action="store_true",
        help="Skip the frontend (saves ~5s startup; useful for backend-only e2e)",
    )
    args = parser.parse_args()

    ports = {
        "mock_llm": args.mock_llm_port,
        "backend": args.backend_port,
    }
    if not args.no_frontend:
        ports["frontend"] = args.frontend_port
    _check_ports_free(ports)

    print("┌ DeepTutor — e2e test environment ────────────────────────────────────")
    print(f"│ Mock LLM   http://127.0.0.1:{args.mock_llm_port}")
    print(f"│ Backend    http://127.0.0.1:{args.backend_port}")
    if not args.no_frontend:
        print(f"│ Frontend   http://127.0.0.1:{args.frontend_port}")
    print("└──────────────────────────────────────────────────────────────────────")
    print()

    procs: list[subprocess.Popen[str]] = []
    threads: list[threading.Thread] = []

    def _spawn_logger(prefix: str, p: subprocess.Popen[str]) -> None:
        t = threading.Thread(target=_stream_to_stdout, args=(prefix, p), daemon=True)
        t.start()
        threads.append(t)

    try:
        print("· Starting mock LLM ...")
        mock = _start_mock_llm(args.mock_llm_port)
        procs.append(mock)
        _spawn_logger("mock    ", mock)
        if not _wait_for_port(args.mock_llm_port, timeout_s=10):
            raise SystemExit("✗ Mock LLM failed to start within 10s")
        print(f"  ✓ Mock LLM ready on :{args.mock_llm_port}")

        e2e_env_file = PROJECT_ROOT / ".env.e2e"
        _write_e2e_env_file(e2e_env_file, args.mock_llm_port, args.backend_port)
        print(f"  ✓ Wrote sandboxed env to {e2e_env_file.name}")

        print("· Starting backend ...")
        backend = _start_backend(args.backend_port, args.mock_llm_port, e2e_env_file)
        procs.append(backend)
        _spawn_logger("backend ", backend)
        if not _wait_for_port(args.backend_port, timeout_s=30):
            raise SystemExit("✗ Backend failed to start within 30s")
        print(f"  ✓ Backend ready on :{args.backend_port}")

        if not args.no_frontend:
            print("· Starting frontend ...")
            frontend = _start_frontend(args.frontend_port, args.backend_port)
            procs.append(frontend)
            _spawn_logger("frontend", frontend)
            if not _wait_for_port(args.frontend_port, timeout_s=60):
                raise SystemExit("✗ Frontend failed to start within 60s")
            print(f"  ✓ Frontend ready on :{args.frontend_port}")

        print()
        print("✓ All services ready. Run e2e tests now. Ctrl-C to stop.")
        print()

        # Block until Ctrl-C or any child exits.
        while True:
            for p in procs:
                if p.poll() is not None:
                    raise SystemExit(f"✗ A service exited with code {p.returncode}")
            time.sleep(0.5)

    except KeyboardInterrupt:
        print("\n· Shutting down (SIGINT) ...")
        return 0
    except SystemExit as e:
        print(f"\n{e}")
        return 1
    finally:
        for p in procs:
            with contextlib.suppress(Exception):
                p.send_signal(signal.SIGTERM)
        for p in procs:
            with contextlib.suppress(Exception):
                p.wait(timeout=5)
        for p in procs:
            if p.poll() is None:
                with contextlib.suppress(Exception):
                    p.kill()


if __name__ == "__main__":
    sys.exit(main())
